<?php

return [
   'Shnookerdookies!',
   'Fudge nuggets!',
   'Cheese and rice!',
   'Sugar!',
   'God bless America!',
   'Poo!',
   'Snickerdoodle!',
   'Banana shenanigans!',
   'Six and two is eight!',
   'God bless it!',
   'Barbara Streisand!',
   'Fiddlesticks!',
   'Jiminy Crickets!',
   'Son of a gun!',
   'Egad!',
   'Great Scott!',
   'Caesar’s ghost!',
   'Merlin’s beard!',
   'Merlin’s pants!',
   'Shucks!',
   'Darn!',
   'Dagnabbit!',
   'Dang rabbit!',
   'Dadgummit!',
   'Jumpin’ Jiminy!',
   'Gee willickers!',
   'Gee whiz!',
   'Cheese whiz!',
   'Good night!',
   'Sam Hill!',
   'Son of a bucket!',
   'William Shatner!',
   'Son of a motherless goat!',
   'Judas Priest!',
   'Gosh darn it!',
   'Shut the front door!',
   'Holy cow!',
   'Horse pucky!',
   'Geez!',
   'Sufferin’ succotash!',
   'Son of a mother trucker!',
   'Fudge berries!',
   'Geez Terwilligers!',
   'Mothersmucker!',
   'Cornnuts!',
   'Poo on a stick!',
   'Aw, duck water!',
   'Dillweed!',
   'Oh, snap!',
   'OMG!',
   'Fraggle rock!',
   'Phooey!',
   'Bogus!',
   'Bull spit!',
   'Crap!',
   'Crikey!',
   'Scuddle butt!',
   'Shuzzbutt!',
   'Son of a biscuit!',
   'Leapin’ lizards!',
   'Oh my gosh!',
   'Oh my goodness!',
   'Peanut butter and jelly!',
   'Drat!',
   'Oh, man!',
   'Oh, dear!',
   'Criminy!',
   'Mother of pearl!',
   'Tartar sauce!',
   'Fish paste!',
   'Hobknocker!',
   'Pokémon!',
   'Golly gee!',
   'What the frog!',
   'Barnacles!',
   'Eat soap!',
   'Eat slugs!',
   'Go lick a duck!',
   'For Pete’s sake!',
   'I don’t give a Donald Duck!',
   'Cheeses!',
   'Pluck it!',
   'Yuck fou!',
   'Aww, noodles!',
   'Hamburgers!',
   'Geez Louise!',
   'Fishsticks!',
   'Frack!',
   'Jumpin’ Jehoshaphat!',
   'What the cuss!',
   'Narf!',
   'Marklar!',
   'Shitake mushrooms!',
   'Son of a nutcracker!',
   'Raspberries!',
   'Shikaka!',
   'Mecrob!',
   'Dogshit!' // For Ryan
];